name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 24.1
          - 24.2
          - 24.3
          - 24.4
          - 24.5
          - 25.1
          - 25.2
          - 25.3
          - 26.1
          - 26.2
          - 26.3
          - 27.1
          - snapshot
        # include:
        #   - emacs_version: 24.1
        #     lint_ignore: 1
        #   - emacs_version: 24.2
        #     lint_ignore: 1
        python_version:
          - 2.7
          - 3.5
          - 3.6
          - 3.7
          - 3.8
    # env:
    #   EMACS_LINT_IGNORE: ${{ matrix.lint_ignore }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Emacs ${{ matrix.emacs_version }}
      uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v2
      with:
        python-version : ${{ matrix.python_version }}

    - name: Set up Cask
    - uses: conao3/setup-cask@master
    # - name: Run tests
    #   run: './run-tests.sh'
